DROP TABLE IF EXISTS CLIENT;
CREATE TABLE CLIENT(ID
 DECIMAL PRIMARY KEY, NAME VARCHAR(40), SURNAME VARCHAR(40), COUNTRY VARCHAR(65), CITY VARCHAR(65), ADDRESS VARCHAR(255));

DROP TABLE IF EXISTS FILE;
CREATE TABLE FILE(ID DECIMAL PRIMARY KEY, FILEDATE TIMESTAMP, STATUS VARCHAR(15), AMOUNT DOUBLE(30), RESPONSE VARCHAR(255), SOURCE DECIMAL, TARGET DECIMAL);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT(ID DECIMAL PRIMARY KEY, AMOUNT DOUBLE(30), OPENDATE TIMESTAMP, CLOSEDATE TIMESTAMP, STATUS VARCHAR(15), CLIENTFK DECIMAL);

ALTER TABLE ACCOUNT
  ADD FOREIGN KEY (CLIENTFK)
REFERENCES CLIENT (ID);